[build]
  # Build command for your React app
  command = "npm run build"
  # Directory where the build output is located
  publish = "dist"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optional: Handle API routes if you add them later
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Environment variables (if needed)
# [build.environment]
#   NODE_VERSION = "18"